### ISSUE TITLE
Please add them blueprints ;)

### ISSUE THREAD

**Issue by kristianmandrup** [jkatsnelson/ember-cli-emblem#1]
It is just a blueprints folder and a few template files in the right places... ;)

**Comment by tolgaek** [comment]
@kristianmandrup I can maintain this library. I spend a lot of time with Ember and recently switched to using emblem since missing slim mark up from my rails days

**Comment by kristianmandrup** [comment]
Looks like work has been done in other forks of this project. I would recommend someone to take the best of these forks and ask permission to continue from here...

**Comment by buschtoens** [comment]
Uhm, guys, [*there*](https://github.com/Vestorly/ember-cli-emblem-hbs-printer). :smiley:

**Comment by tolgaek** [comment]
@buschtoens Thanks I discovered that like 10 minutes ago. It works perfectly and seems well supported

**Comment by buschtoens** [comment]
@jkatsnelson Oh and btw: I haven't talked to the maintainers of [`ember-cli-emblem-hbs-printer`](https://github.com/Vestorly/ember-cli-emblem-hbs-printer), but maybe they would be up for a name swap.

**Comment by tolgaek** [comment]
I think the npm is the real issue. Seeing 'ember-cli-emblem' makes things the problem. Yeah I think emblem-hbs-printer guys should switch to that name

**Comment by jkatsnelson** [comment]
I am happy to give up the name!

**Comment by buschtoens** [comment]
@jkatsnelson Great news, thanks a lot! And also thanks a lot for having provided this massively useful addon in the past. You rock! :)

I guess we'll now just have to wait for a maintainer to ping back. :)

**Comment by jkatsnelson** [comment]
I haven't removed an npm listing before/done a hand-off, so if the person who would do a hand-off with me wants to ping me here that'd be cool :) or tweet @myowz

**Comment by buschtoens** [comment]
Normally it would just be this:
```
npm owner add mixonic ember-cli-emblem
npm owner add jondayton ember-cli-emblem
npm owner rm jkatsnelson ember-cli-emblem
```

However; I'd definitely wait for a ping back too. :)

**Comment by okolehao** [comment]
Hey @jkatsnelson  we'd be happy to work with you on getting the hand off

**Comment by ahnbizcad** [comment]
Nice lateral, @jkatsnelson 

We're goin' for the touchdown.
